// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// readEDFsamples
DataFrame readEDFsamples(std::string fname);
RcppExport SEXP EDF2R_readEDFsamples(SEXP fnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    __result = Rcpp::wrap(readEDFsamples(fname));
    return __result;
END_RCPP
}
// readEDFevents
DataFrame readEDFevents(std::string fname);
RcppExport SEXP EDF2R_readEDFevents(SEXP fnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    __result = Rcpp::wrap(readEDFevents(fname));
    return __result;
END_RCPP
}
