# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readEDFsamples <- function(fname) {
    .Call('EDF2R_readEDFsamples', PACKAGE = 'EDF2R', fname)
}

readEDFevents <- function(fname) {
    .Call('EDF2R_readEDFevents', PACKAGE = 'EDF2R', fname)
}

